# Generated by Django 3.2.9 on 2021-12-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.TextField(),
        ),
    ]
