# Generated by Django 3.2.9 on 2021-12-11 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0013_alter_criminal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0002_auto_20211211_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
