# Generated by Django 3.2.9 on 2021-12-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminals', '0022_alter_criminal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouseName', models.CharField(max_length=50)),
                ('daughterof', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='mobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicalName', models.CharField(max_length=100)),
                ('vehicalType', models.CharField(max_length=50)),
                ('registrationNo', models.CharField(max_length=50)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidName', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('age', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=60)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='financialdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomesource', models.CharField(max_length=100)),
                ('monthlyexpenses', models.CharField(max_length=100)),
                ('propertyy', models.CharField(max_length=100)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('schoolFrom', models.DateField(blank=True, null=True)),
                ('schoolTo', models.DateField(blank=True, null=True)),
                ('college', models.CharField(max_length=50)),
                ('collegeFrom', models.DateField(blank=True, null=True)),
                ('collegeTo', models.DateField(blank=True, null=True)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('landline', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
    ]
