# Generated by Django 3.2.9 on 2021-12-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateprofile', '0002_spouse_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouse',
            name='age',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
