# Generated by Django 3.2.9 on 2022-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateprofile', '0004_alter_brotherspouse_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auntspouse',
            name='age',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brotherkids',
            name='age',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='brotherspouse',
            name='age',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maternalauntspouse',
            name='age',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maternalunclespouse',
            name='age',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sisterspouse',
            name='age',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unclespouse',
            name='age',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
