# Generated by Django 3.2.9 on 2022-01-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateprofile', '0005_auto_20220109_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalauntkids',
            name='age',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
