# Generated by Django 3.2.9 on 2021-11-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='images/profiles/')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('martial_status', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(default='../static/img.jpg', upload_to='images/attachments/')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
    ]
