# Generated by Django 3.2.9 on 2021-12-09 07:13

import criminals.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=50)),
                ('martial_status', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pending', models.BooleanField(default=0)),
                ('interviewed', models.BooleanField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentname', models.CharField(max_length=50)),
                ('attachment', models.FileField(upload_to=criminals.models.get_upload_path)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='criminalvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidname', models.FileField(upload_to='videos/')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='criminalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/profiles/')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crimname', models.CharField(max_length=300)),
                ('commited_on', models.DateField(blank=True, null=True)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
    ]
