# Generated by Django 3.2.9 on 2022-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='6DDC2A', max_length=100),
        ),
    ]
