# Generated by Django 3.2.9 on 2021-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0002_alter_documents_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='webimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='images/attachments/')),
            ],
        ),
    ]
