# Generated by Django 3.2.9 on 2021-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0003_webimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='webvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
