# Generated by Django 3.2.9 on 2021-12-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0003_criminaladdress'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaladdress',
            name='criminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal'),
            preserve_default=False,
        ),
    ]
