# Generated by Django 3.2.9 on 2021-11-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0004_webvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
