# Generated by Django 3.2.9 on 2021-12-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0004_criminaladdress_criminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='pending',
            field=models.BooleanField(default=1),
        ),
    ]
