# Generated by Django 3.2.9 on 2021-11-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0005_alter_criminal_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='profile_pic',
            field=models.FileField(upload_to='images/profiles/'),
        ),
    ]
