# Generated by Django 3.2.9 on 2021-11-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0006_alter_criminal_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='profile_pic',
            field=models.ImageField(upload_to='images/profiles/'),
        ),
    ]
