# Generated by Django 3.2.9 on 2022-01-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0007_alter_criminal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminalcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='C6987B', max_length=100),
        ),
        migrations.AddField(
            model_name='criminal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminals.criminalcategory'),
        ),
    ]
