# Generated by Django 3.2.9 on 2021-12-01 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminals', '0007_alter_criminal_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webvideo',
            old_name='vid',
            new_name='vidname',
        ),
        migrations.AddField(
            model_name='webvideo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webvideo',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webvideo',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
