# Generated by Django 3.2.9 on 2021-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0008_auto_20211201_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='commited_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
