# Generated by Django 3.2.9 on 2021-12-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0009_crime_commited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webvideo',
            name='user',
        ),
        migrations.AddField(
            model_name='webvideo',
            name='criminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal'),
            preserve_default=False,
        ),
    ]
