# Generated by Django 3.2.9 on 2021-12-09 08:02

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('criminals', '0010_auto_20211209_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='CBE21D', max_length=100),
        ),
    ]
