# Generated by Django 3.2.9 on 2021-12-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0011_auto_20211209_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='187BD6', max_length=100),
        ),
    ]
