# Generated by Django 3.2.9 on 2021-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0015_alter_criminal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='imprisioned',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='FA7C75', max_length=100),
        ),
    ]
