# Generated by Django 3.2.9 on 2021-12-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0016_auto_20211211_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='0411AE', max_length=100),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='imprisioned',
            field=models.BooleanField(default=1),
        ),
    ]
