# Generated by Django 3.2.9 on 2021-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0017_auto_20211211_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='F9284C', max_length=100),
        ),
    ]
