# Generated by Django 3.2.9 on 2021-12-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0021_auto_20211213_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='code',
            field=models.CharField(default='2D6694', max_length=100),
        ),
    ]
